cluster.name: elastic_ha_cluster

path:
  data: /data/
  work: /data/work


shield:
  authc:
    realms:
      default:
        type: esusers
        order: 0

# uncomment to allow anonymous access:
#  anonymous:
#    username: es_admin
#    roles: admin

script:
  inline: on
  indexed: on

marvel.agent.exporters:
  id1:
    type: local
    auth:
      username: es_admin
      password: password

http:
  cors.enabled: true

network.host: _eth0_
